# Import the relevant libraries

In [1]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns
# We can override the default matplotlib styles with those of Seaborn
sns.set()
from sklearn.linear_model import LinearRegression

# Load the data

In [2]:
data = pd.read_csv('multiple_linear_regression.csv')
data.head()

    SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [3]:
data.describe()

               SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

# Declare the dependent and the independent variables

In [4]:
independent_variables = data[['SAT','Rand 1,2,3']]
dependent_variable = data['GPA']

# Regression

In [5]:
regression = LinearRegression()
regression.fit(independent_variables, dependent_variable)

LinearRegression()

# R-squared

In [6]:
regression.score(independent_variables, dependent_variable)

0.4066811952814282

# The formula for adjusted R² is given by:
## Adjusted R² = 1 - [(1 - R²) * (n - 1) / (n - k - 1)]
## Where:
## R² is the R-squared value,
## n is the number of observations,
## k is the number of predictors in the model.

## This formula adjusts the R-squared value based on the number of predictors, providing a more accurate measure of model fit.

In [20]:
r_squared = regression.score(independent_variables, dependent_variable)
print("R-squared:", r_squared)
print("shape of independent variables:", independent_variables.shape)
n = independent_variables.shape[0] # OR len(independent_variables)
print("Number of observations (n):", n)
k = independent_variables.shape[1]
print("Number of predictors (k):", k)
adjusted_r_squared = 1 - ((1-r_squared) * (n -1)/(n - k - 1))
print("Adjusted R-squared:", adjusted_r_squared)

R-squared: 0.4066811952814282
shape of independent variables: (84, 2)
Number of observations (n): 84
Number of predictors (k): 2
Adjusted R-squared: 0.39203134825134

# Coefficients

In [17]:
regression.coef_

array([ 0.00165354, -0.00826982])

In [18]:
regression.intercept_

np.float64(0.29603261264909486)