# Import the relevant libraries

In [21]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns

# We can override the default matplotlib styles with those of Seaborn
sns.set()
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import f_regression
from sklearn.preprocessing import StandardScaler

# Load the data

In [2]:
data = pd.read_csv('real_estate_price_size_year.csv')
data.head()

        price     size  year
0  234314.144   643.09  2015
1  228581.528   656.22  2009
2  281626.336   487.29  2018
3  401255.608  1504.75  2015
4  458674.256  1275.46  2009

In [3]:
data.describe()

               price         size         year
count     100.000000   100.000000   100.000000
mean   292289.470160   853.024200  2012.600000
std     77051.727525   297.941951     4.729021
min    154282.128000   479.750000  2006.000000
25%    234280.148000   643.330000  2009.000000
50%    280590.716000   696.405000  2015.000000
75%    335723.696000  1029.322500  2018.000000
max    500681.128000  1842.510000  2018.000000

# Declare the dependent and the independent variables

In [4]:
independent_variables = data[['size', 'year']]
dependent_variable = data['price']

# Standardize the independent variables

In [5]:
scalar = StandardScaler()
scalar.fit(independent_variables)

StandardScaler()

# The `fit` method computes the mean and standard deviation for each feature in the independent variables, which are then used to standardize the data. After fitting the scaler, we can transform the independent variables to have a mean of zero and a standard deviation of one.

# The `transform` method applies the standardization to the independent variables, resulting in a new dataset where each feature has been scaled accordingly. This standardized dataset can then be used for regression analysis or other machine learning tasks.

In [6]:
independent_variables_scaled = scalar.transform(independent_variables)
independent_variables_scaled

array([[-0.70816415,  0.51006137],
       [-0.66387316, -0.76509206],
       [-1.23371919,  1.14763808],
       [ 2.19844528,  0.51006137],
       [ 1.42498884, -0.76509206],
       [-0.937209  , -1.40266877],
       [-0.95171405,  0.51006137],
       [-0.78328682, -1.40266877],
       [-0.57603328,  1.14763808],
       [-0.53467702, -0.76509206],
       [ 0.69939906, -0.76509206],
       [ 3.33780001, -0.76509206],
       [-0.53467702,  0.51006137],
       [ 0.52699137,  1.14763808],
       [ 1.51100715, -1.40266877],
       [ 1.77668568, -1.40266877],
       [-0.54810263,  1.14763808],
       [-0.77276222, -1.40266877],
       [-0.58004747, -1.40266877],
       [ 0.58943055,  1.14763808],
       [-0.78365788,  0.51006137],
       [-1.02322731,  0.51006137],
       [ 1.19557293,  0.51006137],
       [-1.12884431,  0.51006137],
       [-1.10378093, -0.76509206],
       [ 0.84424715,  1.14763808],
       [-0.95171405,  1.14763808],
       [ 1.62279723,  0.51006137],
       [-0.58004747,  0.51006137],
       [ 2.17014356,  0.51006137],
       [ 0.5306345 , -1.40266877],
       [-0.58004747, -1.40266877],
       [-0.8606021 , -0.76509206],
       [-1.10378093,  0.51006137],
       [ 0.015233  ,  1.14763808],
       [-0.77603429,  1.14763808],
       [-0.10057126, -1.40266877],
       [-0.95387294, -1.40266877],
       [-0.56517136,  1.14763808],
       [-0.5219598 ,  0.51006137],
       [ 0.56983186,  0.51006137],
       [-0.57603328,  1.14763808],
       [-0.10057126, -0.76509206],
       [ 1.62279723, -0.76509206],
       [ 0.69939906,  1.14763808],
       [-0.5219598 ,  0.51006137],
       [-0.7415595 , -0.76509206],
       [-0.5219598 , -1.40266877],
       [-0.7415595 ,  0.51006137],
       [-0.79600403,  0.51006137],
       [-0.69328805,  0.51006137],
       [ 0.56983186,  0.51006137],
       [ 0.56983186, -0.76509206],
       [-0.42214483, -1.40266877],
       [-0.69328805,  0.51006137],
       [ 2.21224194,  1.14763808],
       [ 0.6039356 ,  1.14763808],
       [ 1.45329055,  0.51006137],
       [-0.08495304, -1.40266877],
       [-0.95751607,  0.51006137],
       [-0.08387359,  1.14763808],
       [-0.52125142,  0.51006137],
       [ 1.18939985,  0.51006137],
       [ 0.56983186, -0.76509206],
       [-0.56517136,  0.51006137],
       [-0.08748299,  0.51006137],
       [ 0.52699137, -1.40266877],
       [-1.02285625,  0.51006137],
       [-0.56517136,  1.14763808],
       [ 2.17014356, -1.40266877],
       [ 0.56983186, -0.76509206],
       [-0.70708471, -1.40266877],
       [-0.66387316,  0.51006137],
       [-1.02285625,  0.51006137],
       [-0.56517136,  1.14763808],
       [-0.56517136,  1.14763808],
       [ 1.11464825,  1.14763808],
       [ 1.62279723, -1.40266877],
       [-0.57603328, -0.76509206],
       [ 1.13205431, -1.40266877],
       [-0.58004747, -1.40266877],
       [ 0.90847416,  0.51006137],
       [-0.58004747, -1.40266877],
       [-0.70816415,  1.14763808],
       [-0.56517136,  1.14763808],
       [ 0.52699137,  1.14763808],
       [-1.25915362, -1.40266877],
       [ 0.59162317, -0.76509206],
       [-0.84791862,  1.14763808],
       [ 1.29501685,  1.14763808],
       [-0.53467702,  1.14763808],
       [ 0.73714592,  0.51006137],
       [-0.53467702,  0.51006137],
       [-0.5219598 ,  1.14763808],
       [-0.5219598 , -1.40266877],
       [-1.02285625, -0.76509206],
       [ 0.62208377, -0.76509206],
       [ 2.19844528, -1.40266877],
       [-0.69062317,  0.51006137],
       [-0.49834693, -1.40266877]])

# Regression with standardized independent variables

In [7]:
regression = LinearRegression()
regression.fit(independent_variables_scaled, dependent_variable)

LinearRegression()

# Coefficients of the regression model with standardized independent variables

In [8]:
regression.coef_

array([67501.57614152, 13724.39708231])

In [9]:
regression.intercept_

np.float64(292289.4701599997)

# Summary table with standardized independent variables

In [10]:
regression_summary = pd.DataFrame(data = [['Bias'],['size'],['year']], columns = ['Features'])
regression_summary['Weights'] = regression.intercept_, regression.coef_[0], regression.coef_[1]
regression_summary

  Features        Weights
0     Bias  292289.470160
1     size   67501.576142
2     year   13724.397082

# R-squared with standardized independent variables

In [12]:
r_squared = regression.score(independent_variables_scaled, dependent_variable)
print("R-squared:", r_squared)

R-squared: 0.7764803683276793

# Adjusted R-squared with standardized independent variables

In [13]:
n = independent_variables_scaled.shape[0] # number of observations
k = independent_variables_scaled.shape[1] # number of independent variables
adjusted_r_squared = 1 - (1 - r_squared) * (n - 1)/(n - k -1)
print("Adjusted R-squared:", adjusted_r_squared)

Adjusted R-squared: 0.77187171612825

# Prediction with standardized independent variables

In [14]:
new_data = pd.DataFrame(data = [[750,2009]], columns = ['size', 'year'])
new_data_scaled = scalar.transform(new_data)
new_data_scaled

array([[-0.34752816, -0.76509206]])

# Prediction using the regression model with standardized independent variables

In [15]:
regression.predict(new_data_scaled)

array([258330.34465995])

# Find p-values for the standardized independent variables using F-regression

In [18]:
f_regression_response = f_regression(independent_variables_scaled, dependent_variable)
p_value = f_regression_response[1]
print("P-values for the standardized independent variables:", p_value)
round_p_value = np.round(p_value, 3)
print("Rounded P-values for the standardized independent variables:", round_p_value)

P-values for the standardized independent variables: [8.12763222e-31 3.57340758e-01]
Rounded P-values for the standardized independent variables: [0.    0.357]

# Summary table with standardized independent variables and their p-values

In [20]:
p_value_summary = pd.DataFrame(data = independent_variables.columns.values, columns = ['Features'])
p_value_summary['Cofficients'] = regression.coef_
p_value_summary['P-value'] = round_p_value
p_value_summary

  Features   Cofficients  P-value
0     size  67501.576142    0.000
1     year  13724.397082    0.357